"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { Groupe } from "./utils/returnFetch";
import { useEffect, useState } from "react";
import { fetching } from "./utils/returnFetch";
import Main from "./example";
import { WagmiConfig, createConfig, configureChains, mainnet } from "wagmi";
import { createPublicClient, http } from "viem";
import AppHeader from "./header";
import ThemeContext from "./themeContext";
import { Header } from "next/dist/lib/load-custom-routes";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "BlockLeaks",
//   // description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [groups, setGroups] = useState<Groupe[]>();
  const [isGroups, setIsGroups] = useState<boolean>();

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeContext />
      </body>
    </html>
  );
}
